repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.711
    hooks:
      - id: mypy
        language_version: python3
  - repo: https://github.com/hanshoi/add-ticket-hook
    rev: 01d4259d6d55deda023d8f643861e1d90d1ab99b
    hooks:
      - id: add-ticket
        args: ["-t 'test, lol'", "-s"]
