repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      stages: [commit]
      language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
      - id: flake8
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.711
    hooks:
      - id: mypy
        stages: [commit]
        language_version: python3
  - repo: https://github.com/bagerard/add-ticket-hook
    rev: v0.1.1
    hooks:
      - id: add-ticket
        args: ["--tags='test,lol'"]
